---
- name: Update and configure Ubuntu server
  hosts: servers
  become: true

  tasks:

    - name: Restart Services Automatically after install # Modifies needrestart.conf so that services automatically restart without that annoying popup
      ansible.builtin.lineinfile:
        path: /etc/needrestart/needrestart.conf
        regexp: '^\#\s*\$nrconf\{restart\}\s*=\s*''i'';'  # regex to match the exact line
        line: "$nrconf{restart} = 'a'; # restart the services automatically"

    - name: Update apt cache and packages # Runs apt update and apt upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Allow unattended upgrades # Enables unattended upgrades so that your system is kept up to date
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present

    - name: Extend logical volume # Extends LVM so that you use the full space available 
      community.general.lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: +100%FREE
        resizefs: true

#    - name: Change hostname # Only needed if you wanted to change the hostname you initially specified in the setup. This updates the hostname
#      ansible.builtin.hostname:
#        name: <hostname>

#    - name: Update /etc/hosts file # Only needed if you wanted to change the hostname you initially specified in the setup. This modifies the /etc/hosts file with the new hostname
#      ansible.builtin.lineinfile:
#        path: /etc/hosts
#        line: "{{ ansible_default_ipv4.address }} <hostname>"

    - name: Set timezone to Pacific/Auckland # Sets the timezone to NZ Auckland
      community.general.timezone:
        name: Pacific/Auckland

    - name: Install open-vm-tools # Even though open-vm-tools is installed by default in newer versions of Ubuntu, I just want to make sure it's there.
      ansible.builtin.apt:
        name: open-vm-tools
        state: present

    - name: Configure UFW # Disabled IPv6 rule because I don't have a IPv6 network yet.
      ansible.builtin.blockinfile:
        path: /etc/default/ufw
        block: |
          IPV6=no

    - name: Enable UFW # As below
      community.general.ufw:
        state: enabled
    
    - name: Disable UFW # Enabled and disabled to allow changes to save
      community.general.ufw:
        state: disabled

    - name: Allow SSH connections # Standard SSH rule
      community.general.ufw:
        rule: allow
        port: ssh

    - name: Enable UFW # Enables firewall
      community.general.ufw:
        state: enabled
    
    - name: Install Key # Copies ssh key to remote server
      ansible.posix.authorized_key:
        user: master
        state: present
        key: "{{lookup('file','/home/moneybags/.ssh/isalei_servers.pub')}}" # Performs lookup

    - name: Disable password based auth # Disables password auth for SSH since we are using an SSH key
      ansible.builtin.lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^#\s*PasswordAuthentication\s+yes'
        line: PasswordAuthentication no

    - name: Disable challenge response authentication # Disables Challenge Response Authentication as we don't need it since we have disabled password authentication for SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/ssh_config
        line: ChallengeResponseAuthentication no

    - name: Restart SSH service # Restarts the SSH server so that our changes can take effect
      ansible.builtin.systemd_service:
        state: restarted
        name: ssh