---
- name: Update and configure Ubuntu server
  hosts: servers
  become: true

  tasks:
    - name: Update apt cache and packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Allow unattended upgrades
      apt:
        name: unattended-upgrades
        state: present

    - name: Extend logical volume
      lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: +100%FREE
        resizefs: true

    - name: Change hostname
      hostname:
        name: <hostname>

    - name: Update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} <hostname>"

    - name: Set timezone to Pacific/Auckland
      timezone:
        name: Pacific/Auckland

    - name: Install open-vm-tools
      apt:
        name: open-vm-tools
        state: present

    - name: Configure UFW
      blockinfile:
        path: /etc/default/ufw
        block: |
          IPV6=no

    - name: Enable UFW
      ufw:
        state: enabled
    
    - name: Disable UFW
      ufw:
        state: disabled

    - name: Deny incoming connections by default
      ufw:
        rule: deny
        direction: in

    - name: Allow outgoing connections by default
      ufw:
        rule: allow
        direction: out

    - name: Allow SSH connections
      ufw:
        rule: allow
        port: ssh

    - name: Enable UFW
      ufw:
        state: enabled
---
- name: Update DNS A records on Synology NAS
  hosts: nas  # Use the [nas] group containing your Synology NAS

  tasks:
    - name: Add DNS A record for each host
      shell: |
        /usr/syno/bin/synoddns --add {{ item }}.isalei.tech "{{ hostvars[item].ansible_host }}"
      args:
        executable: /bin/bash
      become: yes
      loop: "{{ groups['servers'] }}"